config/routes.rb
Reciclauc::Application.routes.draw do

  resources :levels

  resources :complaints do
    resources :comments
  end

	match "/404", :to => "errors#not_found"
	match "/500", :to => "errors#internal_server_error"

  
  resources :advertises

  resources :surveys do
    resources :questions
  end

	match "/buildings/:id" => "buildings#show"

  resources :points
  resources :areas
  resources :dumps
  resources :mobile_users
  
  resources :universities do
    resources :reports
    mount Rapidfire::Engine => "/surveys", :as => "rapidfire"
    resources :categories
    resources :types
    resources :complaint_types
    get "statistics/show"
    post "statistics/show"
    post "statistics/campus"
    post "statistics/pors"
    get "statistics/events"
    resources :campuses do
      resources :reports
      resources :pois
      resources :pors
      resources :events
      resources :complaints do
        resources :comments
      end
      resources :buildings do
        resources :floors
      end
    end
  end

  authenticated :user do
    root :to => 'universities#index'
  end

  devise_for :users

  devise_scope :user do
     root :to => "devise/sessions#new" 
  end

  match 'user_admin(/:university_id)' => 'users#university_admin', :as => :university_admin_users
  match 'user_admin_campus(/:campus_id)' => 'users#campus_admin', :as => :campus_admin_users
  match 'user_admin/:university_id/remove_admin' => 'users#university_admin_remove', :as => :university_admin_remove
  match 'user_admin/:campus_id/remove_campus_admin' => 'users#campus_admin_remove', :as => :campus_admin_remove

  resources :users, :except =>[:edit] do
    collection do
      post 'campus_admin_create'
      post 'university_admin_create'
      get 'edit_password_current_user'
      get 'edit_current_user'
      get 'edit_roles_user'
      get 'edit_campuses_user'
      put 'update_current_user'
      put ':id/update_roles_user' => 'users#update_roles_user' , :as => 'update_roles_user'
      put ':id/update_campuses_user' => 'users#update_campuses_user' , :as => 'update_campuses_user'
    end
  end
  
  get "default/index"
  post "dumps/download"
  post "events/download"
  post "api/make_complaint"
  
      match "/api/get_building_floors/:building_id/:api_token" => "api#get_building_floors"
      match "/api/load_week_events/:campus_id/:api_token" => "api#load_week_events"
      match "api/create_test_users/:quantity" => "api#create_test_users"
      match "api/get_game_levels/:api_token" => "api#get_game_levels"
      match "api/load_game/:api_token/:access_token" => "api#load_game"
      match "api/show_profile/:university_id/:api_token" => "api#show_profile"
      match "api/get_complaint_types/:university_id/:api_token" => "api#get_complaint_types"
      match "api/make_complaint/:api_token" => "api#make_complaint"
      match "api/my_recycle_info/:university_id/:api_token" => "api#my_recycle_info"
      match "api/my_events_info/:university_id/:api_token" => "api#my_events_info"
      match "api/recycle/:dump_id/:api_token" => "api#recycle"
      match "api/check_in/:event_id/:api_token" => "api#check_in"
      post "mobile_users/login"
      match "/api/get_universities_and_campuses/:api_token" => "api#get_universities_and_campuses"
      match "/api/get_campus_buildings/:campus_id/:university_id/:api_token" => "api#get_campus_buildings"
      match "/api/get_universities/:api_token" => "api#get_universities"
      match "/api/get_campuses/:api_token" => "api#get_campuses"
      match "/api/load_campus_points/:campus_id/:api_token" => "api#load_campus_points"
      match "/api/load_banner/:campus_id/:api_token" =>"api#load_banner"
      match "/api/get_survey/:campus_survey_id/:api_token" => "api#get_survey"

end

app/models/dump.rb
class Dump < ActiveRecord::Base
  attr_accessible :description, :por_id, :qr_code, :type_id, :visits,:type, :type_s
  belongs_to :type
  belongs_to :por
  
  validates_presence_of :type_id

  #atributos virtual
  def type_s
  	return self.type.name
  end
end

app/controllers/dumps_controller.rb
class DumpsController < ApplicationController
  # GET /dumps
  # GET /dumps.json
  def index
    authorize! :index, Dump, :message => 'Acceso denegado.'
    @dumps = Dump.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dumps }
    end
  end

  # GET /dumps/1
  # GET /dumps/1.json
  def show
    @dump = Dump.find(params[:id])
    authorize! :show, @dump, :message => 'Acceso denegado.'
    @id = params[:id]
    @por = Por.find(@dump.por_id)
    @url = "https://chart.googleapis.com/chart?cht=qr&chs=250x250&chl=R-"+@dump.id.to_s

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dump }
      format.js
    end
  end

  # GET /dumps/new
  # GET /dumps/new.json
  def new
    @dump = Dump.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dump }
    end
  end

  # GET /dumps/1/edit
  def edit
    authorize! :edit, @dump, :message => 'Acceso denegado.'
    @dump = Dump.find(params[:id])
  end

  # POST /dumps
  # POST /dumps.json
  def create
    @dump = Dump.new(params[:dump])
    authorize! :create, @dump, :message => 'Acceso denegado.'

    respond_to do |format|
      if @dump.save
        format.html { redirect_to @dump, notice: 'El basurero fue creado exitosamente.' }
        format.json { render json: @dump, status: :created, location: @dump }
      else
        format.html { render action: "new" }
        format.json { render json: @dump.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dumps/1
  # PUT /dumps/1.json
  def update
    @dump = Dump.find(params[:id])
    authorize! :update, @dump, :message => 'Acceso denegado.'

    respond_to do |format|
      if @dump.update_attributes(params[:dump])
        format.html { redirect_to @dump, notice: 'El basurero fue modificado exitosamente' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dump.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dumps/1
  # DELETE /dumps/1.json
  def destroy
    @dump = Dump.find(params[:id])
    authorize! :destroy, @dump, :message => 'Acceso denegado.'
    @dump.destroy

    respond_to do |format|
      format.html { redirect_to dumps_url }
      format.json { head :no_content }
    end
  end

  #Metodo para descargar una imagen con el codigo QR asociado al basurero.
  def download
    @dump= Dump.find(params[:dump_id])
    authorize! :download, @dump, :message => 'Acceso denegado.'
    @por = Por.find(@dump.por_id)
    @campus = Campus.find(@por.campus_id)
    @university = University.find(@campus.university_id)

    require 'open-uri'
    @file
    width = params[:width]
    height = params[:height]
    size = width+"x"+height
    @url = "https://chart.googleapis.com/chart?cht=qr&chs="+size+"&chl=R-"+@dump.id.to_s
    
    #Creamos la imagen a partir de la API y las especificaciones del usuario
    open('image.png', 'wb') do |file|
      encoded_url = URI.encode(@url)
      file << open(URI.parse(encoded_url)).read
      @file = file
    end
    
    name = @university.acronym+"_"+@campus.name+"_"+@por.name+"_"+@dump.type.name+"_QR_"+size
    name.to_s
    
    #Abrimos el archivo para enviarlo por send_data
    File.open(@file.path, 'r') do |f|
      send_data f.read, type: "image/png", :filename => name
    end
    #Eliminamos el archivo recien creado para no llenar el servidor
    File.delete(@file.path) if File.exist?(@file.path)
  end

end

app/helpers/dumps_helper.rb
module DumpsHelper
end

app/views/dumps/_dump.html.erb
<div class="por_inner">
<i class="icon-trash"></i> <%= dump.type.name %> <%= link_to '<i class="icon-qrcode"></i>'.html_safe, dump_path(dump), :class => 'btn btn-mini float_right', :data => {:toggle=>"modal", :target => '#modal-qr'},:title => "Codigo QR", remote: true %>
</div>

app/views/dumps/_form.html.erb
<%= form_for @dump, :validate => true do |f| %>
  <% if @dump.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dump.errors.count, "error") %> prohibited this dump from being saved:</h2>

      <ul>
      <% @dump.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :qr_code %><br />
    <%= f.text_field :qr_code %>
  </div>
  <div class="field">
    <%= f.label :type_id %><br />
    <%= f.number_field :type_id %>
  </div>
  <div class="field">
    <%= f.label :por_id %><br />
    <%= f.number_field :por_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dumps/_show.html.erb
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Generar QR</h3>
</div>
<div class="modal-body">
	<p id="notice"><%= notice %></p>

	<row>
	<div class="span6">
	<h4><%=@por.name %></h4>

	<h5>Basurero de <%=@dump.type.name %></h5>

  	<%=form_tag(:controller=> "dumps", :action=> "download", :dump_id => @dump.id) do%>
	  	<%= field_set_tag do %>
	  		<%= label_tag "Ancho" %>
	  		<%= text_field_tag 'width', '400' %>
	  		<%= label_tag "Alto" %>
		  	<%= text_field_tag 'height', '400' %>
		<% end %> 
	  	<button class="btn">Descargar</button>
  	<%end%>
  	</div>
  	<div class="span6"><%= image_tag @url%></div>
  	</row>
</div>
<div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
</div>

app/views/dumps/edit.html.erb
<h1>Editing dump</h1>

<%= render 'form' %>

<%= link_to 'Show', @dump %> |
<%= link_to 'Back', dumps_path %>

app/views/dumps/generate_qr.html.erb
<h2>Código QR para "<%=@id%>"</h2>
<%= image_tag(@url) %>
<%= button_to "Imprimir" %>

app/views/dumps/index.html.erb
<h1>Listing dumps</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Qr code</th>
    <th>Type</th>
    <th>Por</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dumps.each do |dump| %>
  <tr>
    <td><%= dump.description %></td>
    <td><%= dump.qr_code %></td>
    <td><%= dump.type_id %></td>
    <td><%= dump.por_id %></td>
    <td><%= link_to 'Show', dump %></td>
    <td><%= link_to 'Edit', edit_dump_path(dump) %></td>
    <td><%= link_to 'Destroy', dump, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dump', new_dump_path %>

app/views/dumps/new.html.erb
<h1>New dump</h1>

<%= render 'form' %>

<%= link_to 'Back', dumps_path %>

app/views/dumps/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div span="span3">
		<p>
		  <b>Punto de Reciclaje:</b>
		  <%= @por.name %>
		</p>

		<p>
		  <b>Descripción:</b>
		  <%= @dump.description %>
		</p>

		<p>
		  <b>Tipo:</b>
		  <%= @dump.type_id %>
		</p>
	</div>
	<div class="span9">
	  <b>Qr code:</b>
	  <%= image_tag(@url) %>
	</div>
</div>

app/views/dumps/show.js.erb
$("#modal-qr").html('<%= j render("show") %>');