config/routes.rb
Reciclauc::Application.routes.draw do

  resources :levels

  resources :complaints do
    resources :comments
  end

	match "/404", :to => "errors#not_found"
	match "/500", :to => "errors#internal_server_error"

  
  resources :advertises

  resources :surveys do
    resources :questions
  end

	match "/buildings/:id" => "buildings#show"

  resources :points
  resources :areas
  resources :dumps
  resources :mobile_users
  
  resources :universities do
    resources :reports
    mount Rapidfire::Engine => "/surveys", :as => "rapidfire"
    resources :categories
    resources :types
    resources :complaint_types
    get "statistics/show"
    post "statistics/show"
    post "statistics/campus"
    post "statistics/pors"
    get "statistics/events"
    resources :campuses do
      resources :reports
      resources :pois
      resources :pors
      resources :events
      resources :complaints do
        resources :comments
      end
      resources :buildings do
        resources :floors
      end
    end
  end

  authenticated :user do
    root :to => 'universities#index'
  end

  devise_for :users

  devise_scope :user do
     root :to => "devise/sessions#new" 
  end

  match 'user_admin(/:university_id)' => 'users#university_admin', :as => :university_admin_users
  match 'user_admin_campus(/:campus_id)' => 'users#campus_admin', :as => :campus_admin_users
  match 'user_admin/:university_id/remove_admin' => 'users#university_admin_remove', :as => :university_admin_remove
  match 'user_admin/:campus_id/remove_campus_admin' => 'users#campus_admin_remove', :as => :campus_admin_remove

  resources :users, :except =>[:edit] do
    collection do
      post 'campus_admin_create'
      post 'university_admin_create'
      get 'edit_password_current_user'
      get 'edit_current_user'
      get 'edit_roles_user'
      get 'edit_campuses_user'
      put 'update_current_user'
      put ':id/update_roles_user' => 'users#update_roles_user' , :as => 'update_roles_user'
      put ':id/update_campuses_user' => 'users#update_campuses_user' , :as => 'update_campuses_user'
    end
  end
  
  get "default/index"
  post "dumps/download"
  post "events/download"
  post "api/make_complaint"
  
      match "/api/get_building_floors/:building_id/:api_token" => "api#get_building_floors"
      match "/api/load_week_events/:campus_id/:api_token" => "api#load_week_events"
      match "api/create_test_users/:quantity" => "api#create_test_users"
      match "api/get_game_levels/:api_token" => "api#get_game_levels"
      match "api/load_game/:api_token/:access_token" => "api#load_game"
      match "api/show_profile/:university_id/:api_token" => "api#show_profile"
      match "api/get_complaint_types/:university_id/:api_token" => "api#get_complaint_types"
      match "api/make_complaint/:api_token" => "api#make_complaint"
      match "api/my_recycle_info/:university_id/:api_token" => "api#my_recycle_info"
      match "api/my_events_info/:university_id/:api_token" => "api#my_events_info"
      match "api/recycle/:dump_id/:api_token" => "api#recycle"
      match "api/check_in/:event_id/:api_token" => "api#check_in"
      post "mobile_users/login"
      match "/api/get_universities_and_campuses/:api_token" => "api#get_universities_and_campuses"
      match "/api/get_campus_buildings/:campus_id/:university_id/:api_token" => "api#get_campus_buildings"
      match "/api/get_universities/:api_token" => "api#get_universities"
      match "/api/get_campuses/:api_token" => "api#get_campuses"
      match "/api/load_campus_points/:campus_id/:api_token" => "api#load_campus_points"
      match "/api/load_banner/:campus_id/:api_token" =>"api#load_banner"
      match "/api/get_survey/:campus_survey_id/:api_token" => "api#get_survey"

end

app/controllers/types_controller.rb
class TypesController < ApplicationController
before_filter :get_university

  def get_university
    @university = University.find(params[:university_id])
  end
  # GET /types
  # GET /types.json
  def index
    authorize! :index, Type, :message => 'Acceso denegado.'
    @types = @university.types

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @types }
      format.js
    end
  end

  # GET /types/1
  # GET /types/1.json
  def show
    @type = @university.types.find(params[:id])
    authorize! :show, @type, :message => 'Acceso denegado.'

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @type }
      format.js
    end
  end

  # GET /types/new
  # GET /types/new.json
  def new
    @type = Type.new
    @modal_title = "Nuevo Tipo de Punto de Reciclaje"

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @type }
      format.js
    end
  end

  # GET /types/1/edit
  def edit
    @type = @university.types.find(params[:id])
    authorize! :edit, @type, :message => 'Acceso denegado.'
    @modal_title = "Editar Tipo de Punto de Reciclaje"
    
    respond_to do |format|
      format.js
    end
  end

  # POST /types
  # POST /types.json
  def create
    @type = @university.types.new(params[:type])
    authorize! :create, @type, :message => 'Acceso denegado.'

    respond_to do |format|
      if @type.save
        format.html { redirect_to university_types_path(@university), notice: 'Tipo creado exitosamente' }
        format.json { render json: @type, status: :created, location: @type }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /types/1
  # PUT /types/1.json
  def update
    @type = @university.types.find(params[:id])
    authorize! :update, @type, :message => 'Acceso denegado.'

    respond_to do |format|
      if @type.update_attributes(params[:type])
        format.html { redirect_to university_types_path(@university), notice: 'Tipo fue editado exitosamente' }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type = @university.types.find(params[:id])
    authorize! :destroy, @type, :message => 'Acceso denegado.'
    @type.destroy

    respond_to do |format|
      format.html { redirect_to university_types_path(@university) }
      format.json { head :no_content }
      format.js
    end
  end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/types/_form.html.erb
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"><%= @modal_title %></h3>
</div>
<div class="modal-body">
  <%= form_for [@university, @type], remote: true do |f| %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% @type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
<% end %>
</div>
<div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Cerrar</button>
    <button class="btn btn-primary" id="type-save">Guardar</button>
</div>

app/views/types/_type.html.erb
<div id="edit_type_<%= type.id %>">
<i class="icon-flag"></i> <%= type.name %><% if controller.controller_name == 'types' %> <%= link_to '<i class="icon-pencil"></i>'.html_safe, edit_university_type_path(type.university, type), :data => {:toggle=>"modal", :target => '#modal-type'}, remote: true %>
	<%= link_to '<i class="icon-remove"></i>'.html_safe, [type.university, type], :confirm => '¿Estás seguro que deseas eliminar este tipo? Esta acción no se puede deshacer.', :method => :delete, remote: true %><% end %><br>
</div>

app/views/types/create.js.erb
$('#modal-type').modal('hide');
$('#types').prepend('<%= j render(@type) %>');

app/views/types/destroy.js.erb
$('#edit_type_<%= @type.id %>').remove();

app/views/types/edit.html.erb
<h1>Editing type</h1>

<%= render 'form' %>


<%= link_to 'Back', university_types_path(@university) %>

app/views/types/edit.js.erb
$('#modal-type').html('<%= j render("form") %>');

app/views/types/index.html.erb
<div class="well well-large span5 offset3">
<h1>Administracion de Tipos</h1>
<div class="barra"></div>

<div id="types" class="types">
  <%= render @types %>
</div>


<br />
<%= link_to '<i class="icon-plus"></i>'.html_safe, new_university_type_path(@university), :class => "btn float_right", :data => {:toggle=>"modal", :target => '#modal-type'}, :title => "Nuevo Tipo", remote: true %> 
</div>

app/views/types/new.html.erb
<h1>New type</h1>

<%= render 'form' %>

<%= link_to 'Back', university_types_path(@university) %>

app/views/types/new.js.erb
$("#modal-type").html('<%= j render("form") %>');

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @type.name %>
</p>

<p>
  <b>Logo:</b>
  <%= @type.logo %>
</p>


<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>

app/views/types/update.js.erb
$('#modal-type').modal('hide');
$('#edit_type_<%= @type.id %>').replaceWith('<%= j render(@type) %>');