config/routes.rb
Reciclauc::Application.routes.draw do

  resources :levels

  resources :complaints do
    resources :comments
  end

	match "/404", :to => "errors#not_found"
	match "/500", :to => "errors#internal_server_error"

  
  resources :advertises

  resources :surveys do
    resources :questions
  end

	match "/buildings/:id" => "buildings#show"

  resources :points
  resources :areas
  resources :dumps
  resources :mobile_users
  
  resources :universities do
    resources :reports
    mount Rapidfire::Engine => "/surveys", :as => "rapidfire"
    resources :categories
    resources :types
    resources :complaint_types
    get "statistics/show"
    post "statistics/show"
    post "statistics/campus"
    post "statistics/pors"
    get "statistics/events"
    resources :campuses do
      resources :reports
      resources :pois
      resources :pors
      resources :events
      resources :complaints do
        resources :comments
      end
      resources :buildings do
        resources :floors
      end
    end
  end

  authenticated :user do
    root :to => 'universities#index'
  end

  devise_for :users

  devise_scope :user do
     root :to => "devise/sessions#new" 
  end

  match 'user_admin(/:university_id)' => 'users#university_admin', :as => :university_admin_users
  match 'user_admin_campus(/:campus_id)' => 'users#campus_admin', :as => :campus_admin_users
  match 'user_admin/:university_id/remove_admin' => 'users#university_admin_remove', :as => :university_admin_remove
  match 'user_admin/:campus_id/remove_campus_admin' => 'users#campus_admin_remove', :as => :campus_admin_remove

  resources :users, :except =>[:edit] do
    collection do
      post 'campus_admin_create'
      post 'university_admin_create'
      get 'edit_password_current_user'
      get 'edit_current_user'
      get 'edit_roles_user'
      get 'edit_campuses_user'
      put 'update_current_user'
      put ':id/update_roles_user' => 'users#update_roles_user' , :as => 'update_roles_user'
      put ':id/update_campuses_user' => 'users#update_campuses_user' , :as => 'update_campuses_user'
    end
  end
  
  get "default/index"
  post "dumps/download"
  post "events/download"
  post "api/make_complaint"
  
      match "/api/get_building_floors/:building_id/:api_token" => "api#get_building_floors"
      match "/api/load_week_events/:campus_id/:api_token" => "api#load_week_events"
      match "api/create_test_users/:quantity" => "api#create_test_users"
      match "api/get_game_levels/:api_token" => "api#get_game_levels"
      match "api/load_game/:api_token/:access_token" => "api#load_game"
      match "api/show_profile/:university_id/:api_token" => "api#show_profile"
      match "api/get_complaint_types/:university_id/:api_token" => "api#get_complaint_types"
      match "api/make_complaint/:api_token" => "api#make_complaint"
      match "api/my_recycle_info/:university_id/:api_token" => "api#my_recycle_info"
      match "api/my_events_info/:university_id/:api_token" => "api#my_events_info"
      match "api/recycle/:dump_id/:api_token" => "api#recycle"
      match "api/check_in/:event_id/:api_token" => "api#check_in"
      post "mobile_users/login"
      match "/api/get_universities_and_campuses/:api_token" => "api#get_universities_and_campuses"
      match "/api/get_campus_buildings/:campus_id/:university_id/:api_token" => "api#get_campus_buildings"
      match "/api/get_universities/:api_token" => "api#get_universities"
      match "/api/get_campuses/:api_token" => "api#get_campuses"
      match "/api/load_campus_points/:campus_id/:api_token" => "api#load_campus_points"
      match "/api/load_banner/:campus_id/:api_token" =>"api#load_banner"
      match "/api/get_survey/:campus_survey_id/:api_token" => "api#get_survey"

end

app/models/building.rb
class Building < ActiveRecord::Base
  has_many :floors, :dependent => :destroy
  belongs_to :campus
  attr_accessible :name, :floors, :floors_attributes, :polygon_s, :polygon, :center_coordinates, :center_longitude,:center_latitude
  accepts_nested_attributes_for :floors, allow_destroy: true
  validates_presence_of :name, :polygon
  validates_uniqueness_of :name, scope: :campus_id 

	# Actualizamos el centro del edificio si es que se actualiza su polígono
	before_save :calculate_center, :if => :polygon_changed?

  self.rgeo_factory_generator = RGeo::Geos.factory_generator(:srid => 4326, :geographic => true)

	# Método para recalcular el centro del polígono asociado al edificio
  def calculate_center
  	# Si no hay un polígono asociado, entonces no hacemos nada
  	if self.polygon == nil
  		return
  	end
  	
  	# Si el campus posee un polígono, entonces procedemos a calcular su centro:
  	# -------------------------------------------------------------------------------------
  	lat = 0				# Suma de las latitudes de todos los puntos
  	lng = 0				# Suma de las longitudes de todos los puntos
  	count = 0			# Cantidad de puntos que componen el polígono
  	
  	points = self.polygon.exterior_ring.points		# Extraemos listado de puntos que componen el polígono
  	points = points[0..-2]												# Quitamos el último punto (es el mismo que el primero)
  	count = points.count													# Cantidad de puntos a promediar
  	
  	# Recorremos el arreglo de puntos y sumamos los valores de latitud y longitud para promediarlos:
  	points.each do |point|
  		lat += point.y
  		lng += point.x
  	end
  	
  	# Promediamos los valores:
  	lat = lat / count
  	lng = lng / count
  	
  	# Finalmente, seteamos el valor de center_coordinates
  	self.center_coordinates = "POINT(" + lng.to_s + " " + lat.to_s + ")"
  end
  
  def encoded_polygon
  	if(self.polygon != nil)
	  	encoded = PolylineEncoder.encode(self.polygon.exterior_ring)
	  	return encoded.inspect[1..-2]
	  else
	  	return nil
	  end
  end
  
  # Atributo virtual para poder acceder al string del polígono, no a la variable
  def polygon_s
  	return self.polygon.to_s
  end
  
  def polygon_s=(value)
  	self.polygon = value
  end

  def center_longitude
    return center_coordinates.x
  end
  def center_latitude
    return center_coordinates.y
  end
  def floors?
    if self.floors.count == 0
      false
    else
      true
    end
  end
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_filter :get_campus

  def get_campus
    @university = University.find(params[:university_id])
    @campus = @university.campuses.find(params[:campus_id])
  end
  
  # GET campuses/1/buildings
  # GET campuses/1/buildings.json
  def index
    authorize! :index, Building, :message => 'Acceso denegado.'
    @buildings = @campus.buildings
    @json_buildings = SmartCampusApi.generate_json_buildings(@buildings, false)
    respond_to do |format|
      format.json 	# index.json.erb
      format.js
    end
  end

  # GET campuses/1/buildings/1
  # GET campuses/1/buildings/1.json
  def show
    @building = @campus.buildings.find(params[:id])
    authorize! :show, @building, :message => 'Acceso denegado.'

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @building }
      format.js
    end
  end

  # GET campuses/1/buildings/new
  # GET campuses/1/buildings/new.json
  def new
    @building = @campus.buildings.build
    @modal_title = "Nuevo Edificio"

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @building }
      format.js
    end
  end

  # GET campuses/1/buildings/1/edit
  def edit
    @building = @campus.buildings.find(params[:id])
    authorize! :edit, @building, :message => 'Acceso denegado.'
    @modal_title = "Editar Edificio"

    respond_to do |format|
      format.js
    end
  end

  # POST campuses/1/buildings
  # POST campuses/1/buildings.json
  def create
		@buildings = @campus.buildings
    @building = @campus.buildings.build(params[:building])
    authorize! :create, @building, :message => 'Acceso denegado.'
    @modal_title = "Nuevo Edificio"

    respond_to do |format|
      if @building.save
        format.html { redirect_to([@building.campus.university,@building.campus, @building], :notice => t("activerecord.alerts.building.created")) }
        format.json { render :json => @building, :status => :created, :location => [@building.campus, @building] }
        format.js
      else
        format.html { render :action => "new" }
        format.json { render :json => @building.errors, :status => :unprocessable_entity }
        format.js		{ render :action => "new" }
      end
    end
  end

  # PUT campuses/1/buildings/1
  # PUT campuses/1/buildings/1.json
  def update
    @building = @campus.buildings.find(params[:id])
    authorize! :update, @building, :message => 'Acceso denegado.'
    @modal_title = "Editar Edificio"

    respond_to do |format|
      if @building.update_attributes(params[:building])
        format.html { redirect_to([@building.campus.university, @building.campus, @building], :notice => t("activerecord.alerts.building.updated")) }
        format.json { head :ok }
        format.js
      else
        format.html { render :action => "edit" }
        format.json { render :json => @building.errors, :status => :unprocessable_entity }
        format.js		{ render :action => "edit" }
      end
    end
  end

  # DELETE campuses/1/buildings/1
  # DELETE campuses/1/buildings/1.json
  def destroy
		@buildings = @campus.buildings
    @building = @campus.buildings.find(params[:id])
    authorize! :destroy, @building, :message => 'Acceso denegado.'
    @building.destroy

    respond_to do |format|
      format.html { redirect_to university_campus_buildings_url(@campus.university, @campus) }
      format.json { head :ok }
      format.js
    end
  end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/_building.html.erb
<div class="accordion-group" id="accordion-border-style">
	<div class="accordion-heading">
	 	<a class="accordion-toggle collapsed campus_component" id="edit_building_<%= building.id %>" data-toggle="collapse" data-parent="#accordion_building" href="#collapse_building_<%= building.id %>">
	        <%= building.name %>
	      </a>
	
		<%= link_to '<i class="icon-trash icon-white"></i>'.html_safe, [building.campus.university, building.campus, building], :class => 'btn btn-mini float_right form_btn delete_btn', :confirm => '¿Estás seguro que deseas eliminar este edificio? Esta acción no se puede deshacer.', :method => :delete,:title => "Eliminar", remote: true %>
		<%= link_to '<i class="icon-pencil icon-white"></i>'.html_safe, edit_university_campus_building_path(building.campus.university, building.campus, building), :class => "btn btn-mini float_right form_btn edit_btn", :data => {:toggle=>"modal", :target => '#modal-building'},:title => "Editar", remote: true %>
    </div>
    <div id="collapse_building_<%= building.id %>" class="accordion-body collapse">
      <div class="accordion-inner">
      	<div id="floors">
	      <% if building.floors? %>
			<%= render building.floors.ordered %>
	      <%else%>
	      	<p>No tiene pisos</p>
	      <%end%>
	  	</div>
	      <%= link_to 'Agregar Piso <i class="icon-cross"></i>'.html_safe, new_university_campus_building_floor_path(building.campus.university, building.campus, building), :class => "btn btn-mini float_right form_btn edit_btn", :data => {:toggle=>"modal", :target => '#modal-building'}, :title => "Nuevo Piso", remote: true %>
      </div>
    </div>
   
  </div>

app/views/buildings/_building_fields.html.erb
<div class="well well-small">
	<%= f.text_field :name %>
	<%= f.link_to_remove '<i class="icon-remove"></i>'.html_safe %>
</div>

app/views/buildings/_floor_fields.html.erb
<fieldset>
  <%= f.label :number, "Floor" %><br />
  <%= f.number_field :number %><br />
   <div class="field">
    <%= f.label :indoor_path %><br />
    <%= f.file_field :indoor_path %>
  </div>
  <%= f.label :description, "Description" %><br />
  <%= f.text_field :description %><br />
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove Building" %>
</fieldset>

app/views/buildings/_form.html.erb
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    
    <h3 id="myModalLabel"><%= @modal_title %></h3>
  </div>
<div class="modal-body">
  <%= link_to 'Ayuda', "#", :class=>"info"%> 
  <div id="polygonMap_canvas" data-map-output="map" class="map_modal"></div>


  <%= simple_form_for [@university, @campus, @building], :validate => true, remote: true do |f| %>
    
    <%= f.error_notification %>
      <%if @building.errors.any?%>
      <div class= "field_with_errors"><%= @building.errors[:polygon][0]%></div>
      <%end%>
    <div class="form-inputs">
    <%= f.input :name, :label=>"Nombre",:placeholder => "Nombre del edificio" %>
    <%= f.hidden_field :polygon_s, "data-map-output" => "polygon" %>
    <button id="reDraw" data-map-input="polygon-redraw" class="btn" aria-hidden="true" disabled="disabled">Redibujar</button>
    </div>

  <% end %>
    
</div>
<div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Cerrar</button>
    <button class="btn btn-primary" id="building-save">Guardar</button>
</div>

app/views/buildings/create.js.erb
// Variables que usaremos para cargar el marcador:
// -----------------------------------------------------------------------------------------
var id = "<%= @building.id %>";										// id del edificio a cargar
var polygon = "<%=@building.encoded_polygon %>";	// polígono asociado al edificio

// Cargamos contenido del modal
$('#modal-building').modal('hide');
$('#accordion_building').prepend('<%= j render(@building) %>');

// Cargamos el edificio en el mapa del campus:
campusMap.loadBuilding(id, polygon);

// Redefinimos la función loadBuildings() para agregar los nuevos edificios dibujados:
function loadBuildings(mapWrapperInstance){
  //agrega polígonos de edificios al mapa
  <% @buildings.each do |building| %>
    var id = "<%= building.id %>";											// id del edificio a cargar
    var polygon = "<%= building.encoded_polygon %>";   	// polígono asociado al edificio

    // Cargamos el edificio en el mapa del campus:
    mapWrapperInstance.loadBuilding(id, polygon);
  <% end %>
}

app/views/buildings/destroy.js.erb
// Variables que usaremos para eliminar el edificio:
// -----------------------------------------------------------------------------------------
var id = "<%= @building.id %>";									// id del edificio a cargar

// Eliminamos el registro del listado de edificios:
$('#edit_building_' + id).parent().parent().remove();

// Quitamos el polígono del mapa del campus:
campusMap.deleteBuilding(id);

// Redefinimos la función loadBuildings() para agregar los nuevos edificios dibujados:
function loadBuildings(mapWrapperInstance){
  //agrega polígonos de edificios al mapa
  <% @buildings.each do |building| %>
    var id = "<%= building.id %>";											// id del edificio a cargar
    var polygon = "<%= building.encoded_polygon %>";   	// polígono asociado al edificio

    // Cargamos el edificio en el mapa del campus:
    mapWrapperInstance.loadBuilding(id, polygon);
  <% end %>
}

app/views/buildings/edit.html.erb
<h1>Editing building</h1>

<%= render 'form' %>

<%= link_to 'Show', [@building.campus.university, @building.campus, @building] %> |
<%= link_to 'Back', university_campus_buildings_path(@building.campus.university, @building.campus) %>

app/views/buildings/edit.js.erb
// Variables que usaremos para cargar el marcador:
// -----------------------------------------------------------------------------------------
var id = "<%= @building.id %>";												// id del edificio a cargar
var polygon = "<%=@building.encoded_polygon %>";			// polígono asociado al edificio
var campusPolygon = "<%=@campus.encoded_polygon %>";	// polígono del campus asociado

// Cargamos contenido del modal
$("#modal-building").html('<%= j render("form") %>');

<% if !@building.errors.any? %>
// Desactivamos el evento 'shown' y lo reactivamos (hacemos esto para subscribirnos una única vez)
$('#modal-building').off('shown');

$('#modal-building').on('shown', function(){

	// Inicializamos el mapa en la posición deseada:
	polygonMap = new MapWrapper('modal-building');
	polygonMap.setCampus(campusPolygon);
	
	// Cargamos los objetos en el fondo del modal:
  loadBuildings(polygonMap);
  loadPois(polygonMap);
  loadPors(polygonMap);
  loadEvents(polygonMap);
	
	// Cargamos polígono asociado en el mapa:
	polygonMap.editBuilding(id, polygon);
});
<% else %>
	// Inicializamos el mapa en la posición deseada:
	polygonMap = new MapWrapper('modal-building');
	polygonMap.setCampus(campusPolygon);
	
	// Cargamos los objetos en el fondo del modal:
  loadBuildings(polygonMap);
  loadPois(polygonMap);
  loadPors(polygonMap);
  loadEvents(polygonMap);
	
	// Si tiene un polígono asociado, lo dibujamos
	<% if @building.encoded_polygon != nil %>
		var id = "new_building";													// id del edificio a cargar
		var polygon = "<%=@building.encoded_polygon %>";	// polígono asociado al edificio
	
		// Cargamos polígono asociado en el mapa:
		polygonMap.editBuilding(id, polygon);		
	<% end %>
<% end %>

//mensaje de ayuda
HelpInfo('-Puedes editar el polígono haciendo click en "redibujar". <br> -Haz click en cada uno de los vértices del edificio para dibujar el polígono que lo delimita.');

app/views/buildings/index.html.erb
<h1><%= link_to @campus.name, [@campus.university, @campus] %></h1>
<h3>Buildings</h3>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
  </tr>

<% @buildings.each do |building| %>
  <tr>
    <td><%= link_to building.name, [building.campus.university, building.campus, building] %></td>
    <td><%= link_to 'Edit', edit_university_campus_building_path(building.campus.university, building.campus, building) %></td>
    <td><%= link_to 'Destroy', [building.campus.university, building.campus, building], :confirm => '¿Estas seguro?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Building', new_university_campus_building_path(params[:campus_id]) %>

app/views/buildings/index.js.erb
$("#buildings").html("<%= escape_javascript(render @buildings) %>");

app/views/buildings/new.html.erb
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	<h3 id="myModalLabel">Nuevo Edificio</h3>
</div>


<%= render 'form' %>

<%= link_to 'Back', university_campus_buildings_path(@building.campus.university, @building.campus) %>

app/views/buildings/new.js.erb
// Variables que usaremos para cargar el marcador:
// -----------------------------------------------------------------------------------------
var campusPolygon = "<%=@campus.encoded_polygon %>";	// polígono del campus asociado
 
// Cargamos contenido del modal
$("#modal-building").html('<%= j render("form") %>');

<% if !@building.errors.any? %> 
// Desactivamos el evento 'shown'
$('#modal-building').off('shown');
// Lo volvemos a reactivar (hacemos esto para subscribirnos una única vez)
$('#modal-building').on('shown', function(){
	// Inicializamos el mapa:
	polygonMap = new MapWrapper('modal-building');
	polygonMap.setCampus(campusPolygon);
	
	// Cargamos los objetos en el fondo del modal:
  loadBuildings(polygonMap);
  loadPois(polygonMap);
  loadPors(polygonMap);
  loadEvents(polygonMap);
});
<% else %>
	// Inicializamos el mapa:
	polygonMap = new MapWrapper('modal-building');
	polygonMap.setCampus(campusPolygon);
	
	// Cargamos los objetos en el fondo del modal:
  loadBuildings(polygonMap);
  loadPois(polygonMap);
  loadPors(polygonMap);
  loadEvents(polygonMap);
	
	// Si tiene un polígono asociado, lo dibujamos
	<% if @building.encoded_polygon != nil %>
		var id = "new_building";													// id del edificio a cargar
		var polygon = "<%=@building.encoded_polygon %>";	// polígono asociado al edificio
	
		// Cargamos polígono asociado en el mapa:
		polygonMap.editBuilding(id, polygon);		
	<% end %>
<% end %>

//mensaje de ayuda
HelpInfo('-Haz click en cada uno de los vértices del edificio para dibujar el polígono que lo delimita. <br> -Puedes comenzar nuevamente haciendo click en "redibujar".');

app/views/buildings/show.html.erb
<p id="notice"><%= notice %></p>

<H1>
  <%= @building.name %>
</H1>

<h6>
  <%= @building.campus.name %>, <%= @university.acronym %>
</h6>
<h4>Floors:</h4>
<ul>
<% @building.floors.each do |floor| %>
  <li><%= floor.number %> <%= link_to floor.description, [@university, @campus, @building, floor] %></li>
<% end %>
</ul>


<%= link_to 'Edit', edit_university_campus_building_path(@university, @building.campus, @building) %> |
<%= link_to 'Back', university_campus_buildings_path(@university, @building.campus) %>

app/views/buildings/update.js.erb
// Variables que usaremos para cargar el marcador:
// -----------------------------------------------------------------------------------------
var id = "<%= @building.id %>";										// id del edificio a cargar
var polygon = "<%=@building.encoded_polygon %>";	// polígono asociado al edificio

// Cargamos contenido del modal
$('#modal-building').modal('hide');
$('#edit_building_<%= @building.id %>').parent().parent().replaceWith('<%= j render(@building) %>');

// Cargamos el edificio en el mapa del campus:
campusMap.loadBuilding(id, polygon);