config/routes.rb
Reciclauc::Application.routes.draw do

  resources :levels

  resources :complaints do
    resources :comments
  end

	match "/404", :to => "errors#not_found"
	match "/500", :to => "errors#internal_server_error"

  
  resources :advertises

  resources :surveys do
    resources :questions
  end

	match "/buildings/:id" => "buildings#show"

  resources :points
  resources :areas
  resources :dumps
  resources :mobile_users
  
  resources :universities do
    resources :reports
    mount Rapidfire::Engine => "/surveys", :as => "rapidfire"
    resources :categories
    resources :types
    resources :complaint_types
    get "statistics/show"
    post "statistics/show"
    post "statistics/campus"
    post "statistics/pors"
    get "statistics/events"
    resources :campuses do
      resources :reports
      resources :pois
      resources :pors
      resources :events
      resources :complaints do
        resources :comments
      end
      resources :buildings do
        resources :floors
      end
    end
  end

  authenticated :user do
    root :to => 'universities#index'
  end

  devise_for :users

  devise_scope :user do
     root :to => "devise/sessions#new" 
  end

  match 'user_admin(/:university_id)' => 'users#university_admin', :as => :university_admin_users
  match 'user_admin_campus(/:campus_id)' => 'users#campus_admin', :as => :campus_admin_users
  match 'user_admin/:university_id/remove_admin' => 'users#university_admin_remove', :as => :university_admin_remove
  match 'user_admin/:campus_id/remove_campus_admin' => 'users#campus_admin_remove', :as => :campus_admin_remove

  resources :users, :except =>[:edit] do
    collection do
      post 'campus_admin_create'
      post 'university_admin_create'
      get 'edit_password_current_user'
      get 'edit_current_user'
      get 'edit_roles_user'
      get 'edit_campuses_user'
      put 'update_current_user'
      put ':id/update_roles_user' => 'users#update_roles_user' , :as => 'update_roles_user'
      put ':id/update_campuses_user' => 'users#update_campuses_user' , :as => 'update_campuses_user'
    end
  end
  
  get "default/index"
  post "dumps/download"
  post "events/download"
  post "api/make_complaint"
  
      match "/api/get_building_floors/:building_id/:api_token" => "api#get_building_floors"
      match "/api/load_week_events/:campus_id/:api_token" => "api#load_week_events"
      match "api/create_test_users/:quantity" => "api#create_test_users"
      match "api/get_game_levels/:api_token" => "api#get_game_levels"
      match "api/load_game/:api_token/:access_token" => "api#load_game"
      match "api/show_profile/:university_id/:api_token" => "api#show_profile"
      match "api/get_complaint_types/:university_id/:api_token" => "api#get_complaint_types"
      match "api/make_complaint/:api_token" => "api#make_complaint"
      match "api/my_recycle_info/:university_id/:api_token" => "api#my_recycle_info"
      match "api/my_events_info/:university_id/:api_token" => "api#my_events_info"
      match "api/recycle/:dump_id/:api_token" => "api#recycle"
      match "api/check_in/:event_id/:api_token" => "api#check_in"
      post "mobile_users/login"
      match "/api/get_universities_and_campuses/:api_token" => "api#get_universities_and_campuses"
      match "/api/get_campus_buildings/:campus_id/:university_id/:api_token" => "api#get_campus_buildings"
      match "/api/get_universities/:api_token" => "api#get_universities"
      match "/api/get_campuses/:api_token" => "api#get_campuses"
      match "/api/load_campus_points/:campus_id/:api_token" => "api#load_campus_points"
      match "/api/load_banner/:campus_id/:api_token" =>"api#load_banner"
      match "/api/get_survey/:campus_survey_id/:api_token" => "api#get_survey"

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :categorizations
	has_many :pois, through: :categorizations
	belongs_to :university
  attr_accessible :description, :logo, :name
end

app/controllers/categories_controller.rb
#coding: utf-8
class CategoriesController < ApplicationController
  before_filter :get_university

  def get_university
    @university = University.find(params[:university_id])
  end
  # GET /categories
  # GET /categories.json
  def index
    authorize! :index, Category, :message => 'Acceso denegado.'
    @categories = @university.categories

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show    
    @category = @university.categories.find(params[:id])
    authorize! :show, @category, :message => 'Acceso denegado.'

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new
    @modal_title = "Nueva Categoria"

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
      format.js
    end
  end

  # GET /categories/1/edit
  def edit
    @category = @university.categories.find(params[:id])
    authorize! :edit, @category, :message => 'Acceso denegado.'
    @modal_title = "Editar Categoria"

    respond_to do |format|
      format.js
    end
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = @university.categories.new(params[:category])
    authorize! :create, @category, :message => 'Acceso denegado.'

    respond_to do |format|
      if @category.save
        format.html { redirect_to university_category_path(@university, @category), notice: 'La categoria fue creada exitosamente.' }
        format.json { render json: @category, status: :created, location: @category }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = @university.categories.find(params[:id])
    authorize! :update, @category, :message => 'Acceso denegado.'

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to university_category_path(@university, @category), notice: 'La categoría fue modificada exitosamente.' }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = @university.categories.find(params[:id])
    authorize! :destroy, @category, :message => 'Acceso denegado.'
    @category.destroy

    respond_to do |format|
      format.html { redirect_to university_categories_path(@university) }
      format.json { head :no_content }
      format.js
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="edit_category_<%= category.id %>">
<i class="icon-flag"></i> <%= category.name %><% if controller.controller_name == 'categories' %> <%= link_to '<i class="icon-pencil"></i>'.html_safe, edit_university_category_path(category.university, category), :data => {:toggle=>"modal", :target => '#modal-category'}, remote: true %>
	<%= link_to '<i class="icon-remove"></i>'.html_safe, [category.university, category], :confirm => '¿Estás seguro que deseas eliminar esta categoría? Esta acción no se puede deshacer.', :method => :delete, remote: true %><% end %><br>
</div>

app/views/categories/_form.html.erb
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"><%= @modal_title %></h3>
  </div>

  <div class="modal-body">
<%= simple_form_for [@university, @category], :validate => true, remote: true do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.text_field :name, :placeholder => 'Nombre' %>
  </div>

<% end %>
</div>
<div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Cerrar</button>
    <button class="btn btn-primary" id="category-save">Guardar</button>
</div>

app/views/categories/create.js.erb
$('#modal-category').modal('hide');
$('#categories').prepend('<%= j render(@category) %>');

app/views/categories/destroy.js.erb
$('#edit_category_<%= @category.id %>').remove();

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/edit.js.erb
$('#modal-category').html('<%= j render("form") %>');

app/views/categories/index.html.erb
<div class="well span5 offset3">
	<h1>Administracion de Categorias</h1>
	<div class="barra"></div>
	<div class="categories" id="categories">
	  <%= render @categories %>
	</div>
	<%= link_to '<i class="icon-plus"></i>'.html_safe, new_university_category_path(@university), :class => "btn float_right", :data => {:toggle=>"modal", :target => '#modal-category'}, :title => "Nueva Categoria" ,remote: true %> 
</div>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

app/views/categories/new.js.erb
$("#modal-category").html('<%= j render("form") %>');

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>description:</b>
  <%= @category.description %>
</p>

<p>
  <b>Logo:</b>
  <%= @category.logo %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/categories/update.js.erb
$('#modal-category').modal('hide');
$('#edit_category_<%= @category.id %>').replaceWith('<%= j render(@category) %>');